In [1]:
!pip install numpy

In [3]:
import numpy as np
arr = np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
arr = np.arange(1,13)
print(arr)
a = arr.reshape(3,4)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
arr1 = np.zeros((5,5))
print(arr1)
arr2 = np.ones((3,3))
print(arr2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arr = np.eye(4,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
a = np.array([10, 20, 30, 40, 50, 60])
print(a[1:4])

[20 30 40]


In [24]:
import numpy as np
a = np.random.randint(1,50,size=(1,10))
print(a)
print(np.sum(a))
print(np.max(a))
print(np.min(a))

[[29  3  8 17 11 11 30 26 48 38]]
221
48
3


In [33]:
arr = np.array([5,12,18,7,3,25])
print(arr[arr > 10])

[12 18 25]


In [38]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [40]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
d = np.hstack((a,b.T))
print(d)

[[1 2 5]
 [3 4 6]]


In [42]:
import numpy as np
a = np.random.randint(1,101,size = (4,4))
print(a)

[[28 80 72 70]
 [40  5 52 98]
 [21 14 20 79]
 [77  9 78 44]]


In [44]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x + y)
print(x * y)
print(x ** 3)

[5 7 9]
[ 4 10 18]
[ 1  8 27]


In [50]:
import pandas as pd
students = pd.DataFrame({"name":["sidhharth","Laksh","Amit","Yash","Priti"],"age":[22,12,32,18,26],"marks":[85,98,50,45,65]})
students.index = students.index + 1
print(students)

        name  age  marks
1  sidhharth   22     95
2      Laksh   12     98
3       Amit   32     97
4       Yash   18     99
5      Priti   26     89


In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan"],
    "age": [21, 22, 20, 23, 21],
    "marks": [85, 75, 50, 92, 67]
})
df["grade"] = np.where(df["marks"] > 80, "A",
                np.where(df["marks"] > 60, "B", "C"))
print(df) 

    name  age  marks grade
0  Rahul   21     85     A
1  Sneha   22     75     B
2   Aman   20     50     C
3  Priya   23     92     A
4  Karan   21     67     B


In [6]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan"],
    "age": [21, 22, 20, 23, 21],
    "marks": [85, 75, 50, 92, 67]
})
print(df["age"].describe())
print(df["marks"].describe())

count     5.000000
mean     21.400000
std       1.140175
min      20.000000
25%      21.000000
50%      21.000000
75%      22.000000
max      23.000000
Name: age, dtype: float64
count     5.00000
mean     73.80000
std      16.36154
min      50.00000
25%      67.00000
50%      75.00000
75%      85.00000
max      92.00000
Name: marks, dtype: float64


In [9]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan"],
    "age": [21, 22, 20, 23, 21],
    "salary": [85000, 7500, 50000, 92000, 6700]
})
df1 = df[df["salary"] > 50000]
print(df1)

    name  age  salary
0  Rahul   21   85000
3  Priya   23   92000


In [10]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan"],
    "age": [21, 22, 20, 23, 21],
    "salary": [85000, 7500, 50000, 92000, 6700]
})
df1 = df.sort_values(by = "age", ascending=False)
print(df1)

    name  age  salary
3  Priya   23   92000
1  Sneha   22    7500
0  Rahul   21   85000
4  Karan   21    6700
2   Aman   20   50000


In [11]:
df = pd.DataFrame({
    "product": ["Laptop", "Mobile", "Tablet", "Mobile", "Laptop"],
    "region": ["North", "South", "North", "East", "South"],
    "sales": [50000, 30000, 20000, 15000, 40000]
})
result = df.groupby("region")["sales"].sum()
print(result)

region
East     15000
North    70000
South    70000
Name: sales, dtype: int64


In [13]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan","Amit","Laksh","sidhharth","vikas","Ganesh","Gayatri"],
    "age": [21, 22, 20, np.nan,23, np.nan,21,34,56,23,28],
    "salary": [85000, 7500, 50000, 92000, 6700, np.nan, 9900, np.nan, 23000, np.nan, 45000]
})
df["age"] = df["age"].fillna(df["age"].mean())
df["salary"] = df["salary"].fillna(df["salary"].mean())
print(df)

         name        age   salary
0       Rahul  21.000000  85000.0
1       Sneha  22.000000   7500.0
2        Aman  20.000000  50000.0
3       Priya  27.555556  92000.0
4       Karan  23.000000   6700.0
5        Amit  27.555556  39887.5
6       Laksh  21.000000   9900.0
7   sidhharth  34.000000  39887.5
8       vikas  56.000000  23000.0
9      Ganesh  23.000000  39887.5
10    Gayatri  28.000000  45000.0


In [18]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan","Amit","Laksh","sidhharth","vikas","Ganesh","Gayatri"],
    "age": [21, 22, 20, np.nan,23, np.nan,21,34,56,23,28],
    "salary": [85000, 7500, 50000, 92000, 6700, np.nan, 9900, np.nan, 23000, np.nan, 45000]
})
df.to_csv("mydata.csv", index=False)
new_df = pd.read_csv("mydata.csv")
print("Original DataFrame:")
print(df)
print("\nDataFrame after reading from CSV:")
print(new_df)

Original DataFrame:
         name   age   salary
0       Rahul  21.0  85000.0
1       Sneha  22.0   7500.0
2        Aman  20.0  50000.0
3       Priya   NaN  92000.0
4       Karan  23.0   6700.0
5        Amit   NaN      NaN
6       Laksh  21.0   9900.0
7   sidhharth  34.0      NaN
8       vikas  56.0  23000.0
9      Ganesh  23.0      NaN
10    Gayatri  28.0  45000.0

DataFrame after reading from CSV:
         name   age   salary
0       Rahul  21.0  85000.0
1       Sneha  22.0   7500.0
2        Aman  20.0  50000.0
3       Priya   NaN  92000.0
4       Karan  23.0   6700.0
5        Amit   NaN      NaN
6       Laksh  21.0   9900.0
7   sidhharth  34.0      NaN
8       vikas  56.0  23000.0
9      Ganesh  23.0      NaN
10    Gayatri  28.0  45000.0


In [19]:
df = pd.DataFrame({
    "name": ["Rahul", "Sneha", "Aman", "Priya", "Karan","Amit","Laksh","sidhharth","vikas","Ganesh","Gayatri"],
    "age": [21, 22, 20, np.nan,23, np.nan,21,34,56,23,28],
    "salary": [85000, 7500, 50000, 92000, 6700, np.nan, 9900, np.nan, 23000, np.nan, 45000]
})
df = df.rename(columns={"name": "new_name"})
print(df)

     new_name   age   salary
0       Rahul  21.0  85000.0
1       Sneha  22.0   7500.0
2        Aman  20.0  50000.0
3       Priya   NaN  92000.0
4       Karan  23.0   6700.0
5        Amit   NaN      NaN
6       Laksh  21.0   9900.0
7   sidhharth  34.0      NaN
8       vikas  56.0  23000.0
9      Ganesh  23.0      NaN
10    Gayatri  28.0  45000.0


In [22]:
students = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "name": ["Aman", "Sneha", "Rahul", "Priya"],
    "age": [20, 21, 22, 20]
})
marks = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "marks": [85, 76, 90, 67]
})
merged_df = pd.merge(students, marks, on="student_id")
print(merged_df)

   student_id   name  age  marks
0           1   Aman   20     85
1           2  Sneha   21     76
2           3  Rahul   22     90
3           4  Priya   20     67
