In [2]:
!pip freeze

aext-assistant @ file:///C:/b/abs_98xvdek9qa/croot/aext-assistant_1734644152369/work
aext-assistant-server @ file:///C:/b/abs_93twy7n40b/croot/aext-assistant-server_1734640405857/work
aext-core @ file:///C:/b/abs_73k82brgp5/croot/aext-core_1734637800697/work
aext-core-server @ file:///C:/b/abs_e3xgm257mx/croot/aext-core-server_1734635079146/work
aext-panels @ file:///C:/b/abs_e40tdjfcpq/croot/aext-panels_1734643464834/work
aext-panels-server @ file:///C:/b/abs_546lo5c36i/croot/aext-panels-server_1734640142498/work
aext-project-filebrowser-server @ file:///C:/b/abs_11ixe7hbzm/croot/aext-project-filebrowser-server_1734687629540/work/backend_lib/project_filebrowser
aext-share-notebook @ file:///C:/b/abs_fewa44_d8o/croot/aext-share-notebook_1734642886563/work
aext-share-notebook-server @ file:///C:/b/abs_3dkdp713ad/croot/aext-share-notebook-server_1734639662890/work
aext-shared @ file:///C:/b/abs_6bq_wjfbhn/croot/aext-shared_1734628822229/work
aext-toolbox @ file:///C:/b/abs_8ehb5u9xv_/cro

In [4]:
!pip install numpy

In [1]:
import numpy as np
a = np.array([[1,12,3,4],[2,4,7,9]])
print(a)

[[ 1 12  3  4]
 [ 2  4  7  9]]


In [3]:
l = [10, 20, 30, 40, 50]
a = np.array(l)
print(a)
print(a.dtype)

[10 20 30 40 50]
int32


In [4]:
l1 = [6, 7, 8, 9, 10]
a1 = np.array(l1)
print(a1)
print(a1.shape)
print(a1.ndim)

[ 6  7  8  9 10]
(5,)
1


In [5]:
l2 = [[7, 8, 9], [10, 11, 12]]
a2 = np.array(l2)
print(a2)
print(a2.shape)
print(a2.ndim)

[[ 7  8  9]
 [10 11 12]]
(2, 3)
2


In [6]:
l3 = [[[10, 11, 12], [13, 14, 15]]]
a3 = np.array(l3)
print(a3)
print(a3.shape)
print(a3.ndim)

[[[10 11 12]
  [13 14 15]]]
(1, 2, 3)
3


In [7]:
import numpy as np
a = np.array([[[1,2,3,4],[5,6,7,8],[10,11,12,13],[15,16,17,18]]])
b = np.array([[10,20,30,40]])
print(a+b)

[[[11 22 33 44]
  [15 26 37 48]
  [20 31 42 53]
  [25 36 47 58]]]


In [8]:
c = np.array([["Python","Java"],["AI","ML"]])
for i in np.nditer(c):
    print(i)

Python
Java
AI
ML


In [12]:
c = np.array([["Python","Java"],["AI","ML"]])
for idx,val in np.ndenumerate(c):
    print(idx,val)

(0, 0) Python
(0, 1) Java
(1, 0) AI
(1, 1) ML


In [13]:
c = np.array([["Python","Java"],["AI","ML"]])
b = c.copy()
print(c)
print(b)
c[1][1] = "AWS"
print(c)
print(b)

[['Python' 'Java']
 ['AI' 'ML']]
[['Python' 'Java']
 ['AI' 'ML']]
[['Python' 'Java']
 ['AI' 'AWS']]
[['Python' 'Java']
 ['AI' 'ML']]


In [14]:
c = np.array([["Python","Java"],["AI","ML"]])
b = c.view()
print(c)
print(b)
c[1][1] = "AWS"
print(c)
print(b)

[['Python' 'Java']
 ['AI' 'ML']]
[['Python' 'Java']
 ['AI' 'ML']]
[['Python' 'Java']
 ['AI' 'AWS']]
[['Python' 'Java']
 ['AI' 'AWS']]


In [16]:
d = np.array([1,2,5,6])
e = np.array([10,20,50,60])
print(np.concatenate((d,e)))

[ 1  2  5  6 10 20 50 60]


In [18]:
e = np.array([10,20,50,60,70,80,90,100])
split_b = np.split(e,2)
print(split_b)

[array([10, 20, 50, 60]), array([ 70,  80,  90, 100])]


In [22]:
a = np.arange(10,20,2)
np.save("save_data.npy",a)
print(np.load("save_data.npy"))
b = np.array(["Red","Blue","Orange","Green"])
np.savetxt("data1.txt",b,fmt ="%s") 
print(np.loadtxt("data1.txt",dtype=str))

[10 12 14 16 18]
['Red' 'Blue' 'Orange' 'Green']


In [2]:
import numpy as np
list1 = [10, 20, 30, 40, 50]
arr = np.array(list1)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [4]:
list2 = [6, 7, 8, 9, 10]
arr = np.array(list2)
print(arr)
print(arr.shape)
print(arr.ndim)

[ 6  7  8  9 10]
(5,)
1


In [5]:
list3 = [[7, 8, 9], [10, 11, 12]]
arr = np.array(list3)
print(arr)
print(arr.shape)
print(arr.ndim)

[[ 7  8  9]
 [10 11 12]]
(2, 3)
2


In [6]:
list4 = [[[10, 11, 12], [13, 14, 15]]]
arr = np.array(list4)
print(arr)
print(arr.shape)
print(arr.ndim)

[[[10 11 12]
  [13 14 15]]]
(1, 2, 3)
3


In [7]:
list5 = [1, 3, 5, 7, 9]
arr = np.array([[[[[[[[[list5]]]]]]]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[[[[[[[1 3 5 7 9]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 5)
10


In [8]:
list6 = [50, 60, 70, 80, 90]
arr = np.array(list6)
for i in np.ndenumerate(arr):
    print(i)
    

((0,), 50)
((1,), 60)
((2,), 70)
((3,), 80)
((4,), 90)


In [12]:
list7 = [90, 70, 50, 60, 80]
arr = np.array(list7)
arr.sort()
print(arr)
print(arr[::-1])

[50 60 70 80 90]
[90 80 70 60 50]


In [11]:
list8 = [15, 25, 35, 45, 55]
arr = np.array(list8)
print(sum(arr))

175


In [13]:
x = [2, 4, 6, 8, 10]
y = [1, 3, 5, 7, 9]
z = np.add(x,y)
print(z)

[ 3  7 11 15 19]


In [15]:
x = [10, 20, 30, 40, 50]
y = [5, 10, 15, 20, 25]
result = np.subtract(y,x)
print(result)

[ -5 -10 -15 -20 -25]


In [18]:
list9 = [22, 44, 66, 88, 110]
arr = np.array(list9)
print(max(arr))
print(min(arr))

110
22


In [19]:
arr = np.zeros((6))
print(arr)

[0. 0. 0. 0. 0. 0.]


In [21]:
arr = np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
arr = np.array([[2,2],[2,2]])
print(arr * 5)

[[10 10]
 [10 10]]


In [23]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/asus/anaconda3/Library/include
    lib directory: C:/Users/asus/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    

In [24]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

In [4]:
import numpy as np
arr = np.array([1,4,7,9])
result = np.all(arr != 0)
print("Non of elements are zero:",result)

Non of elements are zero: True


In [9]:
arr = np.array([1,3,0,6,8,14])
result = np.any(arr != 0)
print("Any of element is zero:",result)

Any of element is zero: True


In [5]:
import numpy as np
arr = np.array([22,np.nan,33,np.inf,-np.inf,34,-np.inf,456,np.nan])
print(arr)
result = np.isfinite(arr)
print(result)

[ 22.  nan  33.  inf -inf  34. -inf 456.  nan]
[ True False  True False False  True False  True False]


In [6]:
arr = np.array([22,np.nan,33,np.inf,-np.inf,34,-np.inf,456,np.nan])
print(arr)
result = np.isinf(arr)
print(result)

[ 22.  nan  33.  inf -inf  34. -inf 456.  nan]
[False False False  True  True False  True False False]


In [7]:
arr = np.array([22,np.nan,33,np.inf,-np.inf,34,-np.inf,456,np.nan])
print(arr)
result = np.isnan(arr)
print(result)

[ 22.  nan  33.  inf -inf  34. -inf 456.  nan]
[False  True False False False False False False  True]


In [8]:
import numpy as np
arr = np.array([3, 4.5, 2+3j, 7, 9.2, 5+0j])
complex_check = np.iscomplex(arr)
real_check = np.isreal(arr)
x = 10
y = np.array([1, 2, 3])
is_scalar_x = np.isscalar(x)
is_scalar_y = np.isscalar(y)
print("Array:", arr)
print("Complex number check:", complex_check)
print("Real number check:", real_check)
print("Is x scalar?:", is_scalar_x)
print("Is y scalar?:", is_scalar_y)

Array: [3. +0.j 4.5+0.j 2. +3.j 7. +0.j 9.2+0.j 5. +0.j]
Complex number check: [False False  True False False False]
Real number check: [ True  True False  True  True  True]
Is x scalar?: True
Is y scalar?: False


In [10]:
a = np.array([22,44,67,-23,9,-32,9,np.inf])
b = np.array([22,44,67,-23,9,-32,9,np.inf])
print(a == b)
print(np.array_equal(a,b))

[ True  True  True  True  True  True  True  True]
True


In [11]:
arr1 = np.array([1.0, 2.001, 3.0, 4.0])
arr2 = np.array([1.0, 2.0001, 3.0, 3.9999])
tolerance = 0.01
result = np.abs(arr1 - arr2) <= tolerance
print("Element-wise comparison within tolerance:", result)
print("Are all elements equal within tolerance?:", np.all(result))

Element-wise comparison within tolerance: [ True  True  True  True]
Are all elements equal within tolerance?: True


In [12]:
arr1 = np.array([5, 10, 15, 20])
arr2 = np.array([3, 10, 18, 20])
greater = arr1 > arr2
greater_equal = arr1 >= arr2
less = arr1 < arr2
less_equal = arr1 <= arr2
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Greater (arr1 > arr2):", greater)
print("Greater or Equal (arr1 >= arr2):", greater_equal)
print("Less (arr1 < arr2):", less)
print("Less or Equal (arr1 <= arr2):", less_equal)

Array 1: [ 5 10 15 20]
Array 2: [ 3 10 18 20]
Greater (arr1 > arr2): [ True False False False]
Greater or Equal (arr1 >= arr2): [ True  True False  True]
Less (arr1 < arr2): [False False  True False]
Less or Equal (arr1 <= arr2): [False  True  True  True]


In [13]:
arr = np.array([1, 7, 13, 105])
memory_size = arr.nbytes
print("Array:", arr)
print("Total memory occupied (in bytes):", memory_size)

Array: [  1   7  13 105]
Total memory occupied (in bytes): 16


In [14]:
arr = np.arange(30, 71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [15]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr = np.random.rand()
print(arr)

0.013465934602130525


In [21]:
arr = np.random.randn(15)
print(arr)

[-1.35605907 -0.03855639  1.09211944 -0.83346293  0.72053684  0.70636651
  1.28119669 -0.3451548  -1.93524035 -0.43247562 -0.31031982  1.29219526
 -0.27008191  0.27839885  0.56289051]


In [22]:
arr = np.arange(15, 56)
print(arr[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [23]:
arr = np.arange(12).reshape(3, 4)
print("3x4 Array:")
print(arr)
print("\nIterating over the array:")
for row in arr:
    for element in row:
        print(element, end=" ")
    print()

3x4 Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Iterating over the array:
0 1 2 3 
4 5 6 7 
8 9 10 11 


In [24]:
arr = np.linspace(5, 50, 10)
print(arr)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [3]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/asus/anaconda3/Library/include
    lib directory: C:/Users/asus/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    

In [6]:
import numpy as np
arr = np.array([1,5,2,8,11,0])
a1 = np.all(arr != 0)
print(a1)

False


In [8]:
arr = np.array([1,5,2,8,11,12])
a1 = np.any(arr != 0)
print(a1)

True


In [2]:
import numpy as np
r_arr = np.random.rand(1)
print(r_arr)

[0.24933301]


In [4]:
import numpy as np
mean = 200
std_dev = 7
arr = np.random.normal(mean, std_dev, (8, 5))
print("2D Array (8x5) from Normal Distribution (200,7):")
print(arr)

2D Array (8x5) from Normal Distribution (200,7):
[[190.86161706 206.09822739 199.42025358 198.53593187 199.22410033]
 [192.46299953 189.24537872 204.42500458 208.2863794  205.44984646]
 [195.53286546 197.433993   200.27905766 200.48266248 210.88602917]
 [198.95910314 211.30844498 199.65766121 180.61626885 196.62840101]
 [211.03957824 196.70639041 213.2876291  214.03940011 198.39045647]
 [194.34727389 182.79225989 192.43095614 209.14956632 209.66521007]
 [205.82256409 192.26029978 204.23573036 188.90513872 200.7481947 ]
 [193.42193266 195.79788386 201.95449589 200.83665733 199.68708765]]
